length=input("Enter the length of the rectangle: ")
width=input("Enter the width of the rectangle: ")
area = float(length) * float(width)
area=int(area)
print("The area of the rectangle is:", area)   
